// Nombres de ejercicios en español (generados por diccionario de términos de gym).
export default {
"0001": "Abdominal",
"0002": "Flexión lateral",
"0003": "Air bike",
"1512": "All fours squad estiramiento",
"0006": "Alterno heel touchers",
"0007": "Alterno lateral jalón",
"1368": "Ankle círculos",
"3293": "Archer dominada",
"3294": "Archer flexión",
"2355": "De brazo slingers colgado inclinado de rodilla legs",
"2333": "De brazo slingers colgado recto legs",
"3214": "Arms apart circular toe touch",
"3204": "Arms sobre la cabeza completo abdominal",
"0009": "De pecho fondo de rodillas asistido",
"0011": "Colgado de rodilla elevación asistido",
"0010": "Colgado de rodilla elevación con throw abajo asistido",
"1708": "Tumbado calves estiramiento asistido",
"1709": "Tumbado de glúteos estiramiento asistido",
"1710": "Tumbado gluteus y piriformis estiramiento asistido",
"0012": "Tumbado elevación de piernas con lateral throw abajo asistido",
"0013": "Tumbado elevación de piernas con throw abajo asistido",
"0014": "Motion giro ruso asistido",
"0015": "Parallel agarre cerrado dominada asistido",
"0016": "Boca abajo de isquios asistido",
"1713": "Boca abajo tumbado de cuádriceps estiramiento asistido",
"1714": "Boca abajo rectus femoris estiramiento asistido",
"0017": "Dominada asistido",
"1716": "Sentado pectoral major estiramiento con pelota de estabilidad asistido",
"1712": "Lateral tumbado aductor estiramiento asistido",
"1758": "Abdominal asistido",
"1431": "De pie dominada supina asistido",
"1432": "De pie dominada asistido",
"0018": "De pie extensión de tríceps con towel asistido",
"0019": "De tríceps fondo de rodillas asistido",
"2364": "Wide-grip de pecho fondo de rodillas asistido",
"3220": "Astride jumps",
"3672": "De espalda y forth escalón",
"1314": "De espalda extensión en pelota de ejercicio",
"3297": "De espalda en máquina",
"1405": "De espalda pectoral estiramiento",
"1473": "Backward salto",
"0020": "Balance board",
"0968": "Alterno curl de bíceps con banda",
"0969": "Alterno v-up con banda",
"0970": "Dominada con banda asistido",
"0971": "Wheel rollerout con banda asistido",
"1254": "Press de banca con banda",
"0980": "Bent-over de cadera extensión con banda",
"0972": "Bicycle crunch con banda",
"0974": "Close-grip jalón con banda",
"0975": "Close-grip flexión con banda",
"0976": "Curl concentrado con banda",
"3117": "Fixed de espalda agarre cerrado jalón con banda",
"3116": "Fixed de espalda underhand jalón con banda",
"0977": "Frontal elevación lateral con banda",
"0978": "Elevación frontal con banda",
"1408": "De cadera levantamiento con banda",
"0979": "Horizontal pallof press con banda",
"0981": "Jack knife abdominal con banda",
"0983": "De rodillas a una mano de brazo jalón con banda",
"0985": "De rodillas twisting crunch con banda",
"0984": "Tumbado de cadera rotación interna con banda",
"1002": "Tumbado recto elevación de piernas con banda",
"0986": "A una mano de brazo sobre la cabeza curl de bíceps con banda",
"0987": "A una mano de brazo a una mano de pierna split sentadilla con banda",
"0988": "A una mano de brazo de pie bajo remo con banda",
"0989": "A una mano de brazo twisting press de pecho con banda",
"0990": "A una mano de brazo twisting sentado remo con banda",
"0991": "Jalón through con banda",
"0992": "Empuje abdominal con banda",
"0993": "Inverso apertura con banda",
"0994": "Inverso curl de muñeca con banda",
"0996": "Sentado de cadera rotación interna con banda",
"1011": "Sentado giro con banda",
"0997": "Press de hombro con banda",
"1018": "Encogimiento con banda",
"0998": "Lateral extensión de tríceps con banda",
"0999": "A una mano de pierna elevación de gemelos con banda",
"1000": "A una mano de pierna inverso elevación de gemelos con banda",
"1001": "A una mano de pierna split sentadilla con banda",
"1004": "Sentadilla con banda",
"1003": "Sentadilla remo con banda",
"1005": "De pie crunch con banda",
"1022": "De pie deltoides posterior remo con banda",
"1007": "De pie twisting crunch con banda",
"1008": "Step-up con banda",
"1009": "Peso muerto pierna rígida con banda",
"1023": "Recto de espalda peso muerto pierna rígida con banda",
"1010": "Recto de pierna peso muerto con banda",
"1012": "Twisting press sobre la cabeza con banda",
"1369": "A dos manos legs elevación de gemelos under both legs V con banda con banda",
"1013": "Underhand jalón con banda",
"1014": "V-up con banda",
"1015": "Vertical pallof press con banda",
"1016": "Curl de muñeca con banda",
"1017": "Y-raise con banda",
"0023": "Alterno curl de bíceps con barra",
"0024": "Bench sentadilla frontal con barra",
"0025": "Press de banca con barra",
"0026": "Bench sentadilla con barra",
"1316": "Inclinado de brazo pullover con barra",
"0027": "Remo inclinado con barra",
"2407": "Curl de bíceps con de brazo blaster con barra",
"0028": "Cargada y press con barra",
"0029": "Clean-grip sentadilla frontal con barra",
"0030": "Close-grip press de banca con barra",
"0031": "Curl con barra",
"0032": "Peso muerto con barra",
"0033": "Declinado press de banca con barra",
"0034": "Declinado inclinado de brazo pullover con barra",
"0035": "Declinado agarre cerrado a skull press con barra",
"1255": "Declinado pullover con barra",
"0036": "Declinado wide-grip press con barra",
"0037": "Declinado wide-grip pullover con barra",
"0038": "Drag curl con barra",
"1370": "En el suelo elevación de gemelos con barra",
"0039": "Frontal de pecho sentadilla con barra",
"0041": "Elevación frontal con barra",
"0040": "Elevación frontal y pullover con barra",
"0042": "Sentadilla frontal con barra",
"0043": "Completo sentadilla con barra",
"1461": "Completo sentadilla de espalda pov con barra",
"1462": "Completo sentadilla lateral pov con barra",
"1545": "Completo zercher sentadilla con barra",
"1409": "Puente de glúteos con barra",
"3562": "Puente de glúteos a dos manos legs en bench con barra",
"0044": "Buenos días con barra",
"0045": "Guillotine press de banca con barra",
"0046": "Hack sentadilla con barra",
"1436": "Alto sentadilla con barra barra",
"0047": "Inclinado press de banca con barra",
"1719": "Inclinado agarre cerrado press de banca con barra",
"0048": "Inclinado reverse-grip press con barra",
"0049": "Inclinado remo con barra",
"0050": "Inclinado de hombro elevación con barra",
"0051": "Jefferson sentadilla con barra",
"0052": "Jm press de banca con barra",
"0053": "Salto sentadilla con barra",
"1410": "Lateral zancada con barra",
"1435": "Bajo sentadilla con barra barra",
"0054": "Zancada con barra",
"1720": "Tumbado de espalda de head extensión de tríceps con barra",
"0055": "Tumbado close-grip press con barra",
"0056": "Tumbado close-grip extensión de tríceps con barra",
"0057": "Tumbado extensión con barra",
"0058": "Tumbado lifting en de cadera con barra",
"0059": "Tumbado curl predicador con barra",
"0061": "Tumbado extensión de tríceps con barra",
"0060": "Tumbado extensión de tríceps skull crusher con barra",
"0063": "Narrow stance sentadilla con barra",
"0064": "A una mano de brazo remo inclinado con barra",
"0065": "A una mano de brazo en el suelo press con barra",
"0066": "A una mano de brazo lateral peso muerto con barra",
"0067": "A una mano de brazo arranque con barra",
"0068": "A una mano de pierna sentadilla con barra",
"0069": "Sobre la cabeza sentadilla con barra",
"1411": "Palms abajo curl de muñeca sobre a bench con barra",
"1412": "Palms arriba curl de muñeca sobre a bench con barra",
"3017": "Pendlay remo con barra",
"1751": "Pin presses con barra",
"0070": "Curl predicador con barra",
"0071": "Press abdominal con barra",
"0072": "Boca abajo inclinado curl con barra",
"0073": "Pullover con barra",
"0022": "Pullover a press con barra",
"0074": "Rack jalón con barra",
"0075": "Deltoides posterior elevación con barra",
"0076": "Deltoides posterior remo con barra",
"0078": "Posterior zancada con barra",
"0077": "Posterior zancada V con barra",
"0079": "Revers curl de muñeca V con barra",
"2187": "Inverso close-grip press de banca con barra",
"0080": "Inverso curl con barra",
"0118": "Agarre invertido remo inclinado con barra",
"1256": "Agarre invertido declinado press de banca con barra",
"1257": "Agarre invertido inclinado press de banca con barra",
"1317": "Agarre invertido inclinado bench remo con barra",
"1721": "Agarre invertido skullcrusher con barra",
"0081": "Inverso curl predicador con barra",
"0082": "Inverso curl de muñeca con barra",
"0084": "Rollerout con barra",
"0083": "Rollerout desde bench con barra",
"0085": "Peso muerto rumano con barra",
"0086": "Sentado behind head military press con barra",
"0087": "Sentado bradford rocky press con barra",
"0088": "Sentado elevación de gemelos con barra",
"1371": "Sentado elevación de gemelos con barra",
"1718": "Sentado agarre cerrado behind de cuello extensión de tríceps con barra",
"0089": "Sentado close-grip curl concentrado con barra",
"0090": "Sentado buenos días con barra",
"0091": "Sentado press sobre la cabeza con barra",
"0092": "Sentado sobre la cabeza extensión de tríceps con barra",
"0094": "Sentado giro con barra",
"0095": "Encogimiento con barra",
"0096": "Lateral inclinado V con barra",
"0098": "Lateral split sentadilla con barra",
"0097": "Lateral split sentadilla V con barra",
"1756": "A una mano de pierna peso muerto con barra",
"0099": "A una mano de pierna split sentadilla con barra",
"2799": "Sitted alterno elevación de piernas con barra",
"2800": "Sitted alterno elevación de piernas con barra",
"0100": "Skier con barra",
"0101": "Speed sentadilla con barra",
"2810": "Split sentadilla V con barra",
"0102": "Sentadilla en knees con barra",
"2798": "Sentadilla salto escalón posterior zancada con barra",
"0103": "De pie abdominal rollerout con barra",
"0104": "De pie de espalda curl de muñeca con barra",
"0105": "De pie bradford press con barra",
"1372": "De pie elevación de gemelos con barra",
"0106": "De pie agarre cerrado curl con barra",
"1456": "De pie agarre cerrado military press con barra",
"2414": "De pie curl concentrado con barra",
"0107": "De pie elevación frontal sobre head con barra",
"0108": "De pie de pierna elevación de gemelos con barra",
"0109": "De pie sobre la cabeza extensión de tríceps con barra",
"0110": "De pie agarre invertido curl con barra",
"0111": "De pie rocking de pierna elevación de gemelos con barra",
"0112": "De pie giro con barra",
"1629": "De pie agarre abierto curl de bíceps con barra",
"1457": "De pie abierto military press con barra",
"0113": "De pie wide-grip curl con barra",
"0114": "Step-up con barra",
"0115": "Stiff de pierna buenos días con barra",
"0116": "Recto de pierna peso muerto con barra",
"0117": "Peso muerto sumo con barra",
"3305": "Thruster con barra",
"0120": "Remo al mentón con barra",
"0119": "Remo al mentón V con barra",
"0121": "Remo al mentón V con barra",
"0122": "Abierto press de banca con barra",
"1258": "Abierto agarre invertido press de banca con barra",
"0124": "Abierto sentadilla con barra",
"0123": "Wide-grip remo al mentón con barra",
"0126": "Curl de muñeca con barra",
"0125": "Curl de muñeca V con barra",
"0127": "Zercher sentadilla con barra",
"3212": "Basic toe touch",
"0128": "Battling ropes",
"3360": "Bear crawl",
"1259": "Behind head de pecho estiramiento",
"0129": "Bench fondo knees inclinado",
"1399": "Bench fondo en en el suelo",
"0130": "Bench de cadera extensión",
"3019": "Bench pull-ups",
"3639": "Inclinado de rodilla tumbado giro",
"1770": "De bíceps de pierna curl concentrado",
"0139": "De bíceps narrow pull-ups",
"0140": "De bíceps dominada",
"0137": "Body-up",
"3543": "Drop salto sentadilla peso corporal",
"3544": "Inclinado lateral plank peso corporal",
"1771": "De rodillas extensión de tríceps peso corporal",
"1769": "Lateral tumbado curl de bíceps peso corporal",
"3168": "Squatting remo peso corporal",
"3167": "Squatting remo con towel peso corporal",
"1373": "De pie elevación de gemelos peso corporal",
"3156": "De pie close-grip a una mano de brazo remo peso corporal",
"3158": "De pie close-grip remo peso corporal",
"3162": "De pie a una mano de brazo remo peso corporal",
"3161": "De pie a una mano de brazo remo con towel peso corporal",
"3166": "De pie remo peso corporal",
"3165": "De pie remo con towel peso corporal",
"0138": "Bottoms-up",
"1374": "Salto al cajón abajo con a una mano de pierna stabilization",
"2466": "Puente escalador cruzado body",
"1160": "Burpee",
"0870": "Butt-ups",
"1494": "Butterfly yoga pose",
"0148": "Alterno press de hombro en polea",
"0149": "Alterno extensión de tríceps en polea",
"3235": "Inverse curl femoral en polea asistido",
"0150": "Lateral jalón en polea barra",
"0151": "Press de banca en polea",
"1630": "Agarre cerrado curl en polea",
"1631": "Curl concentrado en polea",
"0152": "Concentrado extensión en de rodilla en polea",
"0153": "Cross-over lateral jalón en polea",
"0154": "Cross-over revers apertura en polea",
"0155": "Cross-over variation en polea",
"0868": "Curl en polea",
"0157": "Peso muerto en polea",
"0158": "Declinado apertura en polea",
"1260": "Declinado a una mano de brazo press en polea",
"1261": "Declinado press en polea",
"0159": "Declinado sentado wide-grip remo en polea",
"1632": "Drag curl en polea",
"0160": "En el suelo sentado wide-grip remo en polea",
"0161": "Forward elevación en polea",
"0162": "Elevación frontal en polea",
"0164": "Frontal de hombro elevación en polea",
"0165": "Curl martillo con en polea con cuerda",
"1722": "Alto pulley sobre la cabeza extensión de tríceps en polea",
"0167": "Alto remo de rodillas en polea",
"0168": "De cadera aducción en polea",
"0169": "Inclinado press de banca en polea",
"1318": "Inclinado bench remo en polea",
"0171": "Inclinado apertura en polea",
"0170": "Inclinado apertura en pelota de estabilidad en polea",
"0172": "Inclinado extensión en polea",
"0173": "Inclinado extensión de tríceps en polea",
"0174": "Judo flip en polea",
"0860": "Patada en polea",
"0175": "De rodillas crunch en polea",
"3697": "De rodillas deltoides posterior remo con en polea con cuerda",
"0176": "De rodillas extensión de tríceps en polea",
"2330": "Jalón al pecho completo range de motion en polea",
"0177": "Lateral jalón con attachment en polea con cuerda",
"2616": "Lateral jalón con v-bar en polea",
"0178": "Elevación lateral en polea",
"0179": "Bajo apertura en polea",
"0180": "Bajo sentado remo en polea",
"1634": "Tumbado curl de bíceps en polea",
"0182": "Tumbado close-grip curl en polea",
"0184": "Tumbado extensión pullover con attachment en polea con cuerda",
"0185": "Tumbado apertura en polea",
"0186": "Tumbado extensión de tríceps V en polea",
"0188": "Middle apertura en polea",
"0189": "A una mano de brazo remo inclinado en polea",
"0190": "A una mano de brazo curl en polea",
"1262": "A una mano de brazo declinado de pecho apertura en polea",
"1263": "A una mano de brazo apertura en pelota de ejercicio en polea",
"1264": "A una mano de brazo inclinado apertura en pelota de ejercicio en polea",
"1265": "A una mano de brazo inclinado press en polea",
"1266": "A una mano de brazo inclinado press en pelota de ejercicio en polea",
"0191": "A una mano de brazo lateral bent-over en polea",
"0192": "A una mano de brazo elevación lateral en polea",
"1633": "A una mano de brazo curl predicador en polea",
"1267": "A una mano de brazo press en pelota de ejercicio en polea",
"3563": "A una mano de brazo jalón en polea",
"1635": "A una mano de brazo inverso curl predicador en polea",
"0193": "A una mano de brazo recto de espalda alto remo de rodillas en polea",
"1723": "A una mano de brazo de tríceps extensión en polea",
"1636": "Sobre la cabeza curl en polea",
"1637": "Sobre la cabeza curl en pelota de ejercicio en polea",
"0194": "Sobre la cabeza extensión de tríceps attachment en polea con cuerda",
"1319": "Palm rotational remo en polea",
"0195": "Curl predicador en polea",
"1268": "Press en pelota de ejercicio en polea",
"0196": "Jalón through con en polea con cuerda",
"0198": "Jalón en polea",
"0197": "Jalón pro dorsal en polea barra",
"1638": "Jalón curl de bíceps en polea",
"0201": "Extensión en polea",
"0199": "Extensión recto de brazo V en polea",
"0200": "Extensión con attachment en polea con cuerda",
"0202": "Deltoides posterior remo stirrups en polea",
"0203": "Deltoides posterior remo con en polea con cuerda",
"0204": "Posterior drive en polea",
"0205": "Posterior jalón en polea",
"0873": "Inverso crunch en polea",
"0206": "Inverso curl en polea",
"2406": "Agarre invertido extensión de tríceps en polea sz-bar con de brazo blaster en polea",
"1413": "Inverso a una mano de brazo curl en polea",
"0209": "Inverso curl predicador en polea",
"0210": "Inverso curl de muñeca en polea",
"0207": "Reverse-grip extensión en polea",
"0208": "Reverse-grip recto de espalda sentado alto remo en polea",
"1320": "Crossover sentado remo en polea con cuerda",
"1321": "Elevated sentado remo en polea con cuerda",
"1322": "Extensión inclinado bench remo en polea con cuerda",
"1639": "Martillo curl predicador en polea con cuerda",
"1724": "Alto pulley sobre la cabeza extensión de tríceps en polea con cuerda",
"1725": "Inclinado extensión de tríceps en polea con cuerda",
"1726": "Tumbado en en el suelo extensión de tríceps en polea con cuerda",
"1640": "A una mano de brazo martillo curl predicador en polea con cuerda",
"1323": "Sentado remo en polea con cuerda",
"0211": "Russian twists en pelota de estabilidad en polea",
"2144": "Sentado press de pecho en polea",
"0212": "Sentado crunch en polea",
"1641": "Sentado curl en polea",
"0213": "Sentado alto remo v-bar en polea",
"0214": "Sentado a una mano de brazo alterno remo en polea",
"1642": "Sentado a una mano de brazo curl concentrado en polea",
"1643": "Sentado sobre la cabeza curl en polea",
"0215": "Sentado posterior elevación lateral en polea",
"0861": "Sentado remo en polea",
"0216": "Sentado rotación interna de hombro en polea",
"2399": "Sentado giro en polea",
"0218": "Sentado wide-grip remo en polea",
"0219": "Press de hombro en polea",
"0220": "Encogimiento en polea",
"0222": "Flexión lateral en polea",
"0221": "Flexión lateral crunch bosu en polea",
"0223": "Lateral crunch en polea",
"1717": "Sentadilla remo con attachment en polea con cuerda",
"1644": "Squatting curl en polea",
"0224": "De pie de espalda curl de muñeca en polea",
"1375": "De pie elevación de gemelos en polea",
"0225": "De pie cross-over alto inverso apertura en polea",
"0226": "De pie crunch en polea",
"0874": "De pie crunch con attachment en polea con cuerda",
"0227": "De pie apertura en polea",
"0228": "De pie de cadera extensión en polea",
"0229": "De pie interno curl en polea",
"0230": "De pie levantamiento en polea",
"0231": "De pie a una mano de brazo extensión de tríceps en polea",
"1376": "De pie a una mano de pierna elevación de gemelos en polea",
"0232": "De pie jalón con en polea con cuerda",
"0233": "De pie deltoides posterior remo con en polea con cuerda",
"1727": "De pie agarre invertido a una mano de brazo sobre la cabeza extensión de tríceps en polea",
"0234": "De pie remo v-bar en polea",
"0235": "De pie rotación externa de hombro en polea",
"0236": "De pie giro remo v-bar en polea",
"1269": "De pie arriba recto crossovers en polea",
"0238": "Recto de brazo jalón en polea",
"0237": "Recto de brazo jalón con en polea con cuerda",
"0239": "Recto de espalda sentado remo en polea",
"0240": "Boca arriba inverso apertura en polea",
"2464": "Thibaudeau kayak remo en polea",
"0241": "Extensión de tríceps en polea v-bar en polea",
"2405": "Extensión de tríceps en polea v-bar con de brazo blaster en polea",
"0242": "Tuck inverso crunch en polea",
"0243": "Giro en polea",
"0862": "Giro up-down en polea",
"0244": "Twisting jalón en polea",
"1645": "A dos manos de brazo curl en inclinado bench en polea",
"1728": "A dos manos de brazo de tríceps patada en polea",
"0245": "Underhand jalón en polea",
"1270": "Upper de pecho crossovers en polea",
"1324": "Upper remo en polea",
"0246": "Remo al mentón en polea",
"1325": "Agarre abierto posterior jalón behind de cuello en polea",
"0247": "Curl de muñeca en polea",
"1407": "De gemelos empuje estiramiento con hands against en pared",
"1377": "De gemelos estiramiento con hands against en pared",
"1378": "De gemelos estiramiento con con cuerda",
"0248": "Cambered tumbado remo barra",
"2963": "Captains chair recto elevación de piernas",
"1548": "Chair de pierna extendido estiramiento",
"1271": "De pecho y frontal de de hombro estiramiento",
"0251": "De pecho fondo",
"1430": "De pecho fondo en dip-pull-up cage",
"2462": "De pecho fondo en recto barra",
"1272": "De pecho estiramiento con pelota de ejercicio",
"3216": "De pecho tap flexión",
"1326": "Dominada supina",
"0253": "Chin-ups narrow parallel agarre",
"0257": "Círculos de rodilla estiramiento",
"1273": "Clap flexión",
"0258": "Clock flexión",
"1327": "Agarre cerrado dominada supina",
"0259": "Close-grip flexión",
"2398": "Close-grip flexión en knees",
"0260": "Cocoons",
"1468": "Crab giro toe touch",
"0262": "Cruzado body crunch",
"0267": "Crunch hands sobre la cabeza",
"0271": "Crunch en pelota de estabilidad",
"0272": "Crunch en stability pelota arms recto",
"0274": "Crunch en el suelo",
"3016": "Curl-up",
"3769": "Curtsey sentadilla",
"2331": "Cycle cruzado trainer",
"0276": "Dead bug",
"0277": "Declinado crunch",
"0279": "Declinado flexión",
"0282": "Declinado abdominal",
"1274": "Deep flexión",
"0283": "Diamond flexión",
"0284": "Donkey elevación de gemelos",
"1275": "Drop flexión",
"0285": "Alterno curl de bíceps con mancuerna",
"2403": "Alterno curl de bíceps con de brazo blaster con mancuerna",
"1646": "Alterno martillo curl predicador con mancuerna",
"1647": "Alterno curl predicador con mancuerna",
"1648": "Alterno sentado curl martillo con mancuerna",
"0286": "Alterno lateral press con mancuerna",
"1649": "Alterno curl de bíceps con de pierna raised en pelota de ejercicio con mancuerna",
"1650": "Alterno sentado curl de bíceps en pelota de ejercicio con mancuerna",
"2137": "Arnold press con mancuerna",
"0287": "Arnold press V con mancuerna",
"0288": "Around pullover con mancuerna",
"0289": "Press de banca con mancuerna",
"0290": "Bench sentado press con mancuerna",
"0291": "Bench sentadilla con mancuerna",
"0293": "Remo inclinado con mancuerna",
"1651": "Curl de bíceps zancada con bowling motion con mancuerna",
"1652": "Curl de bíceps en pelota de ejercicio con de pierna raised con mancuerna",
"1653": "Curl de bíceps con stork stance con mancuerna",
"0294": "Curl de bíceps con mancuerna",
"2401": "Curl de bíceps con de brazo blaster con mancuerna",
"1654": "Curl de bíceps inverso con mancuerna",
"1655": "Curl de bíceps sentadilla con mancuerna",
"1656": "Curl de bíceps V sit en bosu con mancuerna",
"1201": "Burpee con mancuerna",
"0295": "Cargada con mancuerna",
"1731": "Agarre cerrado press con mancuerna",
"0296": "Close-grip press con mancuerna",
"0297": "Curl concentrado con mancuerna",
"3635": "Contralateral forward zancada con mancuerna",
"0298": "Cruzado body curl martillo con mancuerna",
"1657": "Cruzado body curl martillo V con mancuerna",
"0299": "Cuban press con mancuerna",
"2136": "Cuban press V con mancuerna",
"0300": "Peso muerto con mancuerna",
"0301": "Declinado press de banca con mancuerna",
"0302": "Declinado apertura con mancuerna",
"0303": "Declinado martillo press con mancuerna",
"1276": "Declinado a una mano de brazo apertura con mancuerna",
"1617": "Declinado a una mano de brazo martillo press con mancuerna",
"0305": "Declinado encogimiento con mancuerna",
"0304": "Declinado encogimiento V con mancuerna",
"0306": "Declinado extensión de tríceps con mancuerna",
"0307": "Declinado giro apertura con mancuerna",
"1437": "Finger curls con mancuerna",
"0308": "Apertura con mancuerna",
"1277": "Apertura en pelota de ejercicio con mancuerna",
"1732": "Forward zancada extensión de tríceps con mancuerna",
"0310": "Elevación frontal con mancuerna",
"0309": "Elevación frontal V con mancuerna",
"0311": "Completo can elevación lateral con mancuerna",
"1760": "Sentadilla goblet con mancuerna",
"0313": "Curl martillo con mancuerna",
"1659": "Curl martillo en pelota de ejercicio con mancuerna",
"0312": "Curl martillo V con mancuerna",
"2402": "Martillo curls con de brazo blaster con mancuerna",
"1664": "Alto curl con mancuerna",
"3545": "Inclinado alterno press con mancuerna",
"0314": "Inclinado press de banca con mancuerna",
"0315": "Inclinado curl de bíceps con mancuerna",
"0316": "Inclinado breeding con mancuerna",
"0318": "Inclinado curl con mancuerna",
"0317": "Inclinado curl V con mancuerna",
"0319": "Inclinado apertura con mancuerna",
"1278": "Inclinado apertura en pelota de ejercicio con mancuerna",
"0320": "Inclinado curl martillo con mancuerna",
"0321": "Inclinado martillo press con mancuerna",
"1618": "Inclinado martillo press en pelota de ejercicio con mancuerna",
"0322": "Inclinado interno curl de bíceps con mancuerna",
"1279": "Inclinado a una mano de brazo apertura con mancuerna",
"1280": "Inclinado a una mano de brazo apertura en pelota de ejercicio con mancuerna",
"1619": "Inclinado a una mano de brazo martillo press con mancuerna",
"1620": "Inclinado a una mano de brazo martillo press en pelota de ejercicio con mancuerna",
"0323": "Inclinado a una mano de brazo elevación lateral con mancuerna",
"1281": "Inclinado a una mano de brazo press con mancuerna",
"1282": "Inclinado a una mano de brazo press en pelota de ejercicio con mancuerna",
"0324": "Inclinado palm-in press con mancuerna",
"1283": "Inclinado press en pelota de ejercicio con mancuerna",
"0325": "Inclinado elevación con mancuerna",
"0326": "Inclinado posterior elevación lateral con mancuerna",
"0327": "Inclinado remo con mancuerna",
"0328": "Inclinado de hombro elevación con mancuerna",
"0329": "Inclinado encogimiento con mancuerna",
"3542": "Inclinado t-raise con mancuerna",
"0330": "Inclinado extensión de tríceps con mancuerna",
"0331": "Inclinado twisted flyes con mancuerna",
"1733": "Inclinado a dos manos de brazo extensión con mancuerna",
"3541": "Inclinado y-raise con mancuerna",
"0332": "Iron cruzado con mancuerna",
"0333": "Patada con mancuerna",
"1734": "Kickbacks en pelota de ejercicio con mancuerna",
"1660": "De rodillas curl de bíceps pelota de ejercicio con mancuerna",
"0334": "Elevación lateral con mancuerna",
"0335": "Lateral a elevación frontal con mancuerna",
"0336": "Zancada con mancuerna",
"1658": "Zancada con curl de bíceps con mancuerna",
"0337": "Tumbado extensión across face con mancuerna",
"1729": "Tumbado alterno extensión con mancuerna",
"0338": "Tumbado elbow press con mancuerna",
"0863": "Tumbado external de hombro rotación con mancuerna",
"0339": "Tumbado femoral con mancuerna",
"0340": "Tumbado martillo press con mancuerna",
"2470": "Tumbado en en el suelo deltoides posterior elevación con mancuerna",
"0341": "Tumbado a una mano de brazo deltoides posterior con mancuerna",
"0343": "Tumbado a una mano de brazo press con mancuerna",
"0342": "Tumbado a una mano de brazo press V con mancuerna",
"0344": "Tumbado a una mano de brazo pronated extensión de tríceps con mancuerna",
"0345": "Tumbado a una mano de brazo posterior elevación lateral con mancuerna",
"0346": "Tumbado a una mano de brazo supinated extensión de tríceps con mancuerna",
"0347": "Tumbado pronation con mancuerna",
"2705": "Tumbado pronation en en el suelo con mancuerna",
"1284": "Tumbado pullover en pelota de ejercicio con mancuerna",
"1328": "Tumbado deltoides posterior remo con mancuerna",
"0348": "Tumbado posterior elevación lateral con mancuerna",
"1735": "Tumbado a una mano extensión con mancuerna",
"0349": "Tumbado supination con mancuerna",
"2706": "Tumbado supination en en el suelo con mancuerna",
"1661": "Tumbado boca arriba curl de bíceps con mancuerna",
"0350": "Tumbado boca arriba curl con mancuerna",
"0351": "Tumbado extensión de tríceps con mancuerna",
"1662": "Tumbado abierto curl con mancuerna",
"0352": "Neutral agarre press de banca con mancuerna",
"1285": "A una mano de brazo bench apertura con mancuerna",
"0292": "A una mano de brazo remo inclinado con mancuerna",
"1286": "A una mano de brazo de pecho apertura en pelota de ejercicio con mancuerna",
"0353": "A una mano de brazo curl concentrado en pelota de estabilidad con mancuerna",
"1287": "A una mano de brazo declinado press de pecho con mancuerna",
"1288": "A una mano de brazo apertura en pelota de ejercicio con mancuerna",
"1736": "A una mano de brazo french press en pelota de ejercicio con mancuerna",
"1663": "A una mano de brazo martillo curl predicador con mancuerna",
"1621": "A una mano de brazo martillo press en pelota de ejercicio con mancuerna",
"1289": "A una mano de brazo inclinado press de pecho con mancuerna",
"0354": "A una mano de brazo patada con mancuerna",
"0355": "A una mano de brazo elevación lateral con mancuerna",
"0356": "A una mano de brazo elevación lateral con support con mancuerna",
"1290": "A una mano de brazo press en pelota de ejercicio con mancuerna",
"1665": "A una mano de brazo boca abajo curl con mancuerna",
"1666": "A una mano de brazo boca abajo curl martillo con mancuerna",
"1291": "A una mano de brazo pullover en pelota de ejercicio con mancuerna",
"0358": "A una mano de brazo inverso curl de muñeca con mancuerna",
"0359": "A una mano de brazo inverso apertura con support con mancuerna",
"1622": "A una mano de brazo agarre invertido press con mancuerna",
"1414": "A una mano de brazo inverso curl predicador con mancuerna",
"1667": "A una mano de brazo inverso spider curl con mancuerna",
"1668": "A una mano de brazo sentado curl de bíceps en pelota de ejercicio con mancuerna",
"1669": "A una mano de brazo sentado curl martillo con mancuerna",
"1415": "A una mano de brazo sentado neutral curl de muñeca con mancuerna",
"0361": "A una mano de brazo press de hombro con mancuerna",
"0360": "A una mano de brazo press de hombro V con mancuerna",
"3888": "A una mano de brazo arranque con mancuerna",
"1670": "A una mano de brazo de pie curl con mancuerna",
"1671": "A una mano de brazo de pie curl martillo con mancuerna",
"0362": "A una mano de brazo extensión de tríceps en bench con mancuerna",
"0363": "A una mano de brazo remo al mentón con mancuerna",
"0364": "A una mano de brazo curl de muñeca con mancuerna",
"1672": "A una mano de brazo zottman curl predicador con mancuerna",
"1292": "A una mano de pierna apertura en pelota de ejercicio con mancuerna",
"0365": "Sobre bench neutral curl de muñeca con mancuerna",
"0366": "Sobre bench a una mano de brazo neutral curl de muñeca con mancuerna",
"1441": "Sobre bench a una mano de brazo inverso curl de muñeca con mancuerna",
"0367": "Sobre bench a una mano de brazo curl de muñeca con mancuerna",
"0368": "Sobre bench revers curl de muñeca con mancuerna",
"0369": "Sobre bench curl de muñeca con mancuerna",
"1329": "Palm rotational remo inclinado con mancuerna",
"1623": "Palms en inclinado press de banca con mancuerna",
"0370": "Peacher curl martillo con mancuerna",
"0371": "Plyo sentadilla con mancuerna",
"0372": "Curl predicador con mancuerna",
"1673": "Curl predicador sobre pelota de ejercicio con mancuerna",
"1293": "Press en pelota de ejercicio con mancuerna",
"0373": "Pronate-grip extensión de tríceps con mancuerna",
"0374": "Boca abajo inclinado curl con mancuerna",
"1674": "Boca abajo inclinado curl martillo con mancuerna",
"0375": "Pullover con mancuerna",
"1294": "Pullover de cadera extensión en pelota de ejercicio con mancuerna",
"1295": "Pullover en pelota de ejercicio con mancuerna",
"1700": "Empuje press con mancuerna",
"0376": "Elevación con mancuerna",
"2292": "Deltoides posterior elevación con mancuerna",
"0377": "Deltoides posterior row_shoulder con mancuerna",
"0378": "Posterior apertura con mancuerna",
"0380": "Posterior elevación lateral con mancuerna",
"0379": "Posterior elevación lateral support head con mancuerna",
"0381": "Posterior zancada con mancuerna",
"0382": "Revers agarre curl de bíceps con mancuerna",
"1624": "Inverso press de banca con mancuerna",
"0383": "Inverso apertura con mancuerna",
"1330": "Agarre invertido inclinado bench a una mano de brazo remo con mancuerna",
"1331": "Agarre invertido inclinado bench a dos manos de brazo remo con mancuerna",
"2327": "Agarre invertido remo con mancuerna",
"0384": "Inverso curl predicador con mancuerna",
"1675": "Inverso spider curl con mancuerna",
"0385": "Inverso curl de muñeca con mancuerna",
"1459": "Peso muerto rumano con mancuerna",
"0386": "Rotación inverso apertura con mancuerna",
"2397": "Scott press con mancuerna",
"0387": "Sentado alterno elevación frontal con mancuerna",
"1676": "Sentado alterno curl martillo en pelota de ejercicio con mancuerna",
"0388": "Sentado alterno press con mancuerna",
"3546": "Sentado alterno de hombro con mancuerna",
"0389": "Sentado bench extensión con mancuerna",
"2317": "Sentado inclinado de brazo elevación lateral con mancuerna",
"1730": "Sentado inclinado sobre alterno patada con mancuerna",
"1737": "Sentado inclinado sobre extensión de tríceps con mancuerna",
"1677": "Sentado curl de bíceps con mancuerna",
"0390": "Sentado curl de bíceps en pelota de estabilidad con mancuerna",
"3547": "Sentado curl de bíceps a press de hombro con mancuerna",
"1379": "Sentado elevación de gemelos con mancuerna",
"0391": "Sentado curl con mancuerna",
"0392": "Sentado elevación frontal con mancuerna",
"1678": "Sentado curl martillo con mancuerna",
"0393": "Sentado interno curl de bíceps con mancuerna",
"0394": "Sentado patada con mancuerna",
"0396": "Sentado elevación lateral con mancuerna",
"0395": "Sentado elevación lateral V con mancuerna",
"0397": "Sentado neutral curl de muñeca con mancuerna",
"1679": "Sentado a una mano de brazo curl de bíceps en pelota de ejercicio con de pierna raised con mancuerna",
"0398": "Sentado a una mano de brazo patada con mancuerna",
"0399": "Sentado a una mano de brazo rotate con mancuerna",
"0400": "Sentado a una mano de pierna elevación de gemelos con mancuerna",
"1380": "Sentado a una mano de pierna elevación de gemelos martillo agarre con mancuerna",
"1381": "Sentado a una mano de pierna elevación de gemelos palm arriba con mancuerna",
"0401": "Sentado palms arriba curl de muñeca con mancuerna",
"0402": "Sentado curl predicador con mancuerna",
"0403": "Sentado revers agarre curl concentrado con mancuerna",
"1738": "Sentado agarre invertido a una mano de brazo sobre la cabeza extensión de tríceps con mancuerna",
"0405": "Sentado press de hombro con mancuerna",
"0404": "Sentado press de hombro parallel agarre con mancuerna",
"2188": "Sentado extensión de tríceps con mancuerna",
"0406": "Encogimiento con mancuerna",
"0407": "Flexión lateral con mancuerna",
"0408": "Lateral tumbado a una mano hand elevación con mancuerna",
"3664": "Lateral plank con posterior apertura con mancuerna",
"3548": "A una mano de brazo sobre la cabeza carry con mancuerna",
"0409": "A una mano de pierna elevación de gemelos con mancuerna",
"1757": "A una mano de pierna peso muerto con mancuerna",
"2805": "A una mano de pierna peso muerto con stepbox support con mancuerna",
"0410": "A una mano de pierna split sentadilla con mancuerna",
"0411": "A una mano de pierna sentadilla con mancuerna",
"0413": "Sentadilla con mancuerna",
"3560": "De pie alterno curl martillo y press con mancuerna",
"0414": "De pie alterno press sobre la cabeza con mancuerna",
"0415": "De pie alterno elevación con mancuerna",
"1739": "De pie alterno de tríceps patada con mancuerna",
"2143": "De pie around world con mancuerna",
"1740": "De pie inclinado sobre a una mano de brazo extensión de tríceps con mancuerna",
"1741": "De pie inclinado sobre a dos manos de brazo extensión de tríceps con mancuerna",
"0416": "De pie curl de bíceps con mancuerna",
"0417": "De pie elevación de gemelos con mancuerna",
"0418": "De pie curl concentrado con mancuerna",
"0419": "De pie elevación frontal above head con mancuerna",
"2321": "De pie interno curl de bíceps V con mancuerna",
"0420": "De pie patada con mancuerna",
"0421": "De pie a una mano de brazo curl concentrado con mancuerna",
"0422": "De pie a una mano de brazo curl sobre inclinado bench con mancuerna",
"1680": "De pie a una mano de brazo curl sobre inclinado bench con mancuerna",
"0423": "De pie a una mano de brazo extensión con mancuerna",
"0424": "De pie a una mano de brazo palm en press con mancuerna",
"0425": "De pie a una mano de brazo inverso curl con mancuerna",
"0426": "De pie press sobre la cabeza con mancuerna",
"0427": "De pie palms en press con mancuerna",
"0428": "De pie curl predicador con mancuerna",
"0429": "De pie inverso curl con mancuerna",
"0430": "De pie extensión de tríceps con mancuerna",
"2293": "De pie zottman curl predicador con mancuerna",
"1684": "Escalón arriba a una mano de pierna balance con curl de bíceps con mancuerna",
"0431": "Step-up con mancuerna",
"2796": "Step-up zancada con mancuerna",
"2812": "Step-up split sentadilla con mancuerna",
"0432": "Peso muerto pierna rígida con mancuerna",
"0433": "Recto de brazo pullover con mancuerna",
"0434": "Recto de pierna peso muerto con mancuerna",
"2808": "Sumo jalón through con mancuerna",
"2803": "Supported sentadilla con mancuerna",
"0436": "Tate press con mancuerna",
"1742": "De tríceps patada con stork stance con mancuerna",
"1743": "Twisting press de banca con mancuerna",
"0437": "Remo al mentón con mancuerna",
"1765": "Remo al mentón de espalda pov con mancuerna",
"0864": "Upright rotación externa de hombro con mancuerna",
"5201": "Waiter curl de bíceps con mancuerna",
"0438": "W-press con mancuerna",
"0439": "Zottman curl con mancuerna",
"2294": "Zottman curl predicador con mancuerna",
"2189": "Dumbbells sentado extensión de tríceps",
"1167": "Dinámico de pecho estiramiento",
"3287": "Elbow dips",
"1772": "Elbow levantamiento inverso flexión",
"0443": "Elbow-to-knee",
"3292": "Elevator",
"1332": "Pelota de ejercicio alterno de brazo ups",
"1333": "Pelota de ejercicio de espalda extensión con arms extendido",
"1334": "Pelota de ejercicio de espalda extensión con hands behind head",
"1335": "Pelota de ejercicio de espalda extensión con knees off ground",
"1336": "Pelota de ejercicio de espalda extensión con rotación",
"1744": "Pelota de ejercicio fondo",
"1559": "Pelota de ejercicio de cadera flexor estiramiento",
"1338": "Pelota de ejercicio hug",
"1339": "Pelota de ejercicio dorsal estiramiento",
"1341": "Pelota de ejercicio lower de espalda estiramiento pyramid",
"1342": "Pelota de ejercicio tumbado lateral dorsal estiramiento",
"1382": "Pelota de ejercicio en en pared elevación de gemelos",
"3241": "Pelota de ejercicio en en pared elevación de gemelos tennis pelota between ankles",
"3240": "Pelota de ejercicio en en pared elevación de gemelos tennis pelota between knees",
"1416": "Pelota de ejercicio a una mano de pierna boca abajo lower body rotación",
"1417": "Pelota de ejercicio a una mano legged diagonal kick de isquios curl",
"1296": "Pelota de ejercicio pike flexión",
"1343": "Pelota de ejercicio boca abajo elevación de piernas",
"1560": "Pelota de ejercicio sentado de isquios estiramiento",
"1745": "Pelota de ejercicio sentado de tríceps estiramiento",
"1746": "Pelota de ejercicio boca arriba extensión de tríceps",
"1747": "French press en pelota de ejercicio barra",
"3010": "Tumbado inclinado arms pullover barra",
"1748": "Tumbado agarre cerrado extensión de tríceps behind head barra",
"1344": "Agarre invertido remo inclinado barra",
"1682": "Sentado agarre cerrado curl concentrado barra",
"1749": "De pie french press barra",
"0445": "Anti gravity press barra",
"1627": "Agarre cerrado curl predicador barra",
"0446": "Close-grip curl barra",
"0447": "Curl barra",
"0448": "Declinado agarre cerrado face press barra",
"2186": "Declinado extensión de tríceps barra",
"0449": "Inclinado extensión de tríceps barra",
"0450": "Jm press de banca barra",
"0451": "Agarre invertido curl barra",
"0452": "Agarre invertido curl predicador barra",
"1458": "Sentado curls barra",
"0453": "Sentado extensión de tríceps barra",
"0454": "Spider curl barra",
"1628": "Spider curl barra",
"2404": "Ez-bar curl de bíceps con de brazo blaster",
"2432": "Ez-bar close-grip press de banca",
"2741": "Ez-barbell de pie agarre abierto curl de bíceps",
"2133": "Farmers caminata",
"0455": "Finger curls",
"3303": "Flag",
"0456": "Flexión de pierna abdominal inclinado de rodilla",
"0457": "Flexión de pierna abdominal recto de brazo",
"0458": "En el suelo apertura con con barra",
"0459": "Flutter kicks",
"1472": "Forward salto",
"3470": "Forward zancada",
"3194": "Frankenstein sentadilla",
"2429": "Frog crunch",
"3301": "Frog planche",
"3296": "Frontal en máquina",
"3295": "Frontal en máquina reps",
"0464": "Frontal plank con giro",
"3315": "Completo maltese",
"3299": "Completo planche",
"3327": "Completo planche flexión",
"0466": "Gironda sternum chin",
"3561": "Puente de glúteos march",
"3523": "Puente de glúteos a dos manos legs en bench",
"3193": "Glute-ham elevación",
"0467": "Gorilla chin",
"0469": "Groin crunch",
"1383": "Hack elevación de gemelos",
"1384": "Hack a una mano de pierna elevación de gemelos",
"3221": "Half de rodilla bends",
"3202": "Half abdominal",
"1511": "De isquios estiramiento",
"2139": "Hands bike",
"3218": "Hands clasped circular toe touch",
"3215": "Hands reversed clasped circular toe touch",
"3302": "Handstand",
"0471": "Handstand flexión",
"1764": "Colgado de pierna de cadera elevación",
"0472": "Colgado elevación de piernas",
"1761": "Colgado oblicuo de rodilla elevación",
"0473": "Colgado pike",
"0474": "Colgado recto de pierna de cadera elevación",
"0475": "Colgado recto elevación de piernas",
"0476": "Colgado recto twisting de pierna de cadera elevación",
"3636": "Alto de rodilla against en pared",
"0484": "De cadera elevación inclinado de rodilla",
"1418": "Hug keens a de pecho",
"3234": "Hyght apertura con mancuerna",
"0489": "Hyperextension",
"0488": "Hyperextension en bench",
"3289": "Impossible dips",
"1471": "Inchworm",
"3698": "Inchworm V",
"0490": "Inclinado close-grip flexión",
"0491": "Inclinado de pierna de cadera elevación de pierna recto",
"0492": "Inclinado flexión depth salto",
"0493": "Inclinado flexión",
"3785": "Inclinado flexión en box",
"0494": "Inclinado agarre invertido flexión",
"3011": "Inclinado scapula flexión",
"0495": "Inclinado twisting abdominal",
"1564": "Intermediate de cadera flexor y de cuádriceps estiramiento",
"0496": "Inverse curl femoral bench support",
"2400": "Inverse curl femoral en dominada en polea máquina",
"0499": "Inverted remo",
"2300": "Inverted remo inclinado knees",
"2298": "Inverted remo en bench",
"0497": "Inverted remo V",
"0498": "Inverted remo con straps",
"1419": "Iron cruzado estiramiento",
"1297": "Isométrico de pecho squeeze",
"0500": "Isométrico wipers",
"0501": "Jack burpee",
"3224": "Jack salto",
"0507": "Jackknife abdominal",
"0508": "Janda abdominal",
"2612": "Salto con cuerda",
"0514": "Salto sentadilla",
"0513": "Salto sentadilla V",
"0517": "Advanced windmill con kettlebell",
"0518": "Alterno hang cargada con kettlebell",
"0520": "Alterno press con kettlebell",
"0519": "Alterno press en en el suelo con kettlebell",
"0521": "Alterno renegade remo con kettlebell",
"0522": "Alterno remo con kettlebell",
"0523": "Arnold press con kettlebell",
"0524": "Inclinado press con kettlebell",
"0525": "Bottoms arriba cargada desde hang position con kettlebell",
"0526": "Double alterno hang cargada con kettlebell",
"0527": "Double jerk con kettlebell",
"0528": "Double empuje press con kettlebell",
"0529": "Double arranque con kettlebell",
"0530": "Double windmill con kettlebell",
"0531": "Extendido range a una mano de brazo press en en el suelo con kettlebell",
"0532": "Figure con kettlebell",
"0533": "Sentadilla frontal con kettlebell",
"0534": "Sentadilla goblet con kettlebell",
"0535": "Hang cargada con kettlebell",
"0536": "Zancada pass through con kettlebell",
"0537": "A una mano de brazo cargada y jerk con kettlebell",
"1298": "A una mano de brazo en el suelo press con kettlebell",
"0538": "A una mano de brazo jerk con kettlebell",
"0539": "A una mano de brazo military press a lateral con kettlebell",
"0540": "A una mano de brazo empuje press con kettlebell",
"0541": "A una mano de brazo remo con kettlebell",
"0542": "A una mano de brazo arranque con kettlebell",
"0543": "Pirate supper legs con kettlebell",
"0544": "Pistol sentadilla con kettlebell",
"0545": "Plyo flexión con kettlebell",
"0546": "Sentado press con kettlebell",
"1438": "Sentado a dos manos de brazo military press con kettlebell",
"0547": "Seesaw press con kettlebell",
"0548": "Sumo alto jalón con kettlebell",
"0549": "Balanceo con kettlebell",
"0550": "Thruster con kettlebell",
"0551": "Turkish get arriba sentadilla style con kettlebell",
"0552": "A dos manos de brazo cargada con kettlebell",
"0553": "A dos manos de brazo military press con kettlebell",
"1345": "A dos manos de brazo remo con kettlebell",
"0554": "Windmill con kettlebell",
"0555": "Kick afuera sit",
"0558": "Kipping muscle arriba",
"3640": "De rodilla touch crunch",
"1420": "De rodillas salto sentadilla",
"1346": "De rodillas dorsal estiramiento",
"3239": "De rodillas plank tap de hombro",
"3211": "De rodillas flexión",
"3288": "Korean dips",
"3418": "L-pull-up",
"3419": "L-sit en en el suelo",
"0562": "Landmine",
"3237": "Landmine elevación lateral",
"3300": "Lean planche",
"2271": "Left hook. boxing",
"0570": "De pierna jalón en flat bench",
"1576": "De pierna arriba de isquios estiramiento",
"2287": "En máquina alterno press de pierna",
"0571": "En máquina alterno narrow agarre sentado remo",
"0572": "En máquina dominada supina asistido",
"0573": "En máquina de espalda extensión",
"0574": "En máquina remo inclinado",
"3200": "En máquina remo inclinado con v-bar",
"0575": "En máquina curl de bíceps",
"2289": "En máquina de gemelos press",
"0577": "En máquina press de pecho",
"0576": "En máquina press de pecho",
"0578": "En máquina peso muerto",
"1300": "En máquina declinado press de pecho",
"1253": "En máquina donkey elevación de gemelos",
"0579": "En máquina frontal jalón",
"0580": "En máquina gripless encogimiento",
"1439": "En máquina gripless encogimiento V",
"2288": "En máquina gripper hands",
"1615": "En máquina martillo agarre curl predicador",
"0581": "En máquina alto remo",
"2286": "En máquina de cadera extensión V",
"2611": "En máquina horizontal a una mano press de pierna",
"1299": "En máquina inclinado press de pecho",
"1479": "En máquina inclinado press de pecho V",
"0582": "En máquina de rodillas curl femoral",
"0583": "En máquina de rodillas giro",
"0584": "En máquina elevación lateral",
"0585": "En máquina extensión de pierna",
"0586": "En máquina tumbado curl femoral",
"3195": "En máquina tumbado two-one curl femoral",
"0587": "En máquina military press",
"0588": "En máquina narrow agarre sentado remo",
"0589": "En máquina a una mano de brazo remo inclinado",
"1356": "En máquina a una mano de brazo lateral alto remo",
"1347": "En máquina a una mano de brazo lateral abierto jalón",
"0590": "En máquina a una mano de brazo press de hombro",
"0591": "En máquina overhand de tríceps fondo",
"0592": "En máquina curl predicador",
"1614": "En máquina curl predicador V",
"2285": "En máquina pullover",
"2736": "En máquina agarre invertido lateral jalón",
"1616": "En máquina agarre invertido curl predicador",
"1348": "En máquina agarre invertido vertical remo",
"0593": "En máquina inverso hyperextension",
"1349": "En máquina inverso t-bar remo",
"2315": "En máquina rotary de gemelos",
"2335": "En máquina sentado de gemelos press",
"0594": "En máquina sentado elevación de gemelos",
"1452": "En máquina sentado crunch",
"0595": "En máquina sentado crunch de pecho pad",
"3760": "En máquina sentado crunch V",
"1451": "En máquina sentado fondo",
"0596": "En máquina sentado apertura",
"3759": "En máquina sentado buenos días",
"0597": "En máquina sentado de cadera abducción",
"0598": "En máquina sentado de cadera aducción",
"0599": "En máquina sentado curl femoral",
"0600": "En máquina sentado elevación de piernas crunch",
"0602": "En máquina sentado inverso apertura",
"0601": "En máquina sentado inverso apertura parallel agarre",
"1350": "En máquina sentado remo",
"1385": "En máquina sentado sentadilla elevación de gemelos en press de pierna máquina",
"0603": "En máquina press de hombro",
"0869": "En máquina press de hombro V",
"2318": "En máquina press de hombro V",
"0604": "En máquina encogimiento",
"0605": "En máquina de pie elevación de gemelos",
"3758": "En máquina de pie press de pecho",
"0606": "En máquina t remo barra",
"1351": "En máquina t-bar agarre invertido remo",
"0607": "En máquina extensión de tríceps",
"1313": "En máquina unilateral remo",
"0609": "London puente",
"3013": "Bajo puente de glúteos en en el suelo",
"1352": "Lower de espalda curl",
"3582": "Zancada con salto",
"1688": "Zancada con giro",
"0613": "Tumbado lateral de cuádriceps estiramiento",
"2312": "Tumbado elbow a de rodilla",
"0620": "Tumbado elevación de piernas flat bench",
"0865": "Tumbado leg-hip elevación",
"1301": "Interno press de pecho máquina",
"0624": "March sit en pared",
"1353": "Balón medicinal catch y sobre la cabeza throw",
"1302": "Balón medicinal de pecho pass",
"1303": "Balón medicinal de pecho empuje desde point stance",
"1304": "Balón medicinal de pecho empuje multiple response",
"1305": "Balón medicinal de pecho empuje a una mano response",
"1312": "Balón medicinal de pecho empuje con carrera release",
"1701": "Balón medicinal agarre cerrado flexión",
"1354": "Balón medicinal sobre la cabeza slam",
"1750": "Balón medicinal boca arriba de pecho throw",
"0627": "Mixed agarre dominada supina",
"3217": "Modified hindu flexión",
"1421": "Modified flexión a lower arms",
"0628": "Monster caminata",
"0630": "Escalador",
"0631": "Muscle arriba",
"1401": "Muscle-up en vertical barra",
"2328": "Narrow flexión en pelota de ejercicio",
"1403": "De cuello lateral estiramiento",
"0634": "Negative crunch",
"1495": "Oblicuo crunch V",
"0635": "Oblicuo crunches en el suelo",
"0636": "Olympic curl martillo con barra",
"0637": "Olympic extensión de tríceps con barra",
"1355": "A una mano de brazo against en pared",
"0638": "A una mano de brazo dominada supina",
"0639": "A una mano de brazo fondo",
"0640": "A una mano de brazo slam con balón medicinal",
"1773": "A una mano de brazo towel remo",
"1386": "A una mano de pierna donkey elevación de gemelos",
"1387": "A una mano de pierna en el suelo elevación de gemelos",
"1476": "A una mano de pierna sentadilla",
"0641": "Otis arriba",
"0642": "Outside de pierna kick flexión",
"0643": "Sobre la cabeza de tríceps estiramiento",
"3147": "Pelvic tilt",
"1422": "Pelvic tilt into puente",
"1388": "Peroneals estiramiento",
"3662": "Pike-to-cobra flexión",
"1306": "Plyo flexión",
"1687": "Posterior escalón a sobre la cabeza reach",
"1389": "Posterior tibialis estiramiento",
"3119": "Potty sentadilla",
"3132": "Potty sentadilla con support",
"0648": "Power cargada",
"3665": "Power point plank",
"3203": "Prisoner half abdominal",
"1707": "Boca abajo giro en pelota de estabilidad",
"0651": "Dominada neutral agarre",
"0650": "Pull-in en pelota de estabilidad",
"0652": "Dominada",
"1689": "Empuje y jalón peso corporal",
"3638": "Empuje a carrera",
"1307": "Flexión en bosu",
"0662": "Flexión",
"0653": "Flexión bosu",
"0655": "Flexión en pelota de estabilidad",
"0656": "Flexión en pelota de estabilidad",
"0659": "Flexión en pared",
"0658": "Flexión en pared V",
"0660": "Flexión close-grip off con mancuerna",
"0661": "Flexión inside de pierna kick",
"0663": "Flexión balón medicinal",
"1467": "Flexión en lower arms",
"3145": "Flexión plus",
"0664": "Flexión a lateral plank",
"3533": "De cuádriceps",
"3201": "Quarter abdominal",
"3552": "Quick feet V",
"0666": "Elevación a una mano de brazo flexión",
"0668": "Posterior declinado puente",
"0669": "Deltoides posterior estiramiento",
"0670": "Posterior dominada",
"1582": "Reclining big toe pose con con cuerda",
"3236": "Resistance de cadera thrusts en knees con banda",
"3007": "Resistance extensión de pierna con banda",
"3123": "Resistance sentado curl de bíceps con banda",
"3124": "Resistance sentado press de pecho con banda",
"3006": "Resistance sentado de cadera abducción con banda",
"3122": "Resistance sentado press de hombro con banda",
"3144": "Resistance sentado recto de espalda remo con banda",
"0872": "Inverso crunch",
"0672": "Inverso fondo",
"0673": "Agarre invertido jalón al pecho máquina",
"0674": "Agarre invertido dominada",
"0675": "Inverso hyper extensión en pelota de estabilidad",
"1423": "Inverso hyper en flat bench",
"3663": "Inverso plank con de pierna levantamiento",
"0677": "Ring dips",
"2571": "Rocking frog estiramiento",
"0678": "Rocky dominada jalón",
"2208": "Rodillo de espalda estiramiento",
"2204": "Rodillo body saw",
"2205": "Rodillo de cadera dorsal estiramiento",
"2202": "Rodillo de cadera estiramiento",
"2206": "Rodillo inverso crunch",
"2203": "Rodillo sentado de hombro flexor depresor retractor",
"2209": "Rodillo sentado a una mano de pierna de hombro flexor depresor retractor",
"2207": "Rodillo lateral dorsal estiramiento",
"0680": "Climb con cuerda",
"0685": "Carrera",
"0684": "Carrera equipment",
"1585": "Runners estiramiento",
"0687": "Giro ruso",
"3012": "Scapula dips",
"3021": "Scapula flexión",
"0688": "Scapular dominada",
"3219": "Scissor jumps",
"1390": "Sentado de gemelos estiramiento",
"1424": "Sentado de glúteo estiramiento",
"0689": "Sentado elevación de piernas",
"0690": "Sentado lower de espalda estiramiento",
"2567": "Sentado piriformis estiramiento",
"0691": "Sentado lateral crunch en pared",
"1587": "Sentado abierto angle pose sequence",
"0697": "Self inverse curl femoral asistido",
"1766": "Self inverse curl femoral asistido",
"0696": "Self inverse curl femoral en en el suelo asistido",
"3222": "Semi sentadilla salto",
"3656": "Short stride carrera",
"1763": "De hombro agarre dominada",
"3699": "De hombro tap",
"0699": "De hombro tap flexión",
"1774": "Lateral puente de cadera abducción",
"0705": "Lateral puente V",
"0709": "Lateral de cadera en parallel bars",
"0710": "Lateral de cadera abducción",
"1358": "Lateral tumbado en el suelo estiramiento",
"3667": "Lateral tumbado de cadera aducción",
"1775": "Lateral plank de cadera aducción",
"0716": "Lateral empuje de cuello estiramiento",
"0717": "Lateral flexión",
"0721": "Lateral de muñeca jalón estiramiento",
"0720": "Side-to-side chin",
"3213": "Side-to-side toe touch",
"0725": "A una mano de brazo flexión",
"3645": "A una mano de pierna puente con outstretched de pierna",
"0727": "A una mano de pierna elevación de gemelos en a con mancuerna",
"0730": "A una mano de pierna platform slide",
"1759": "A una mano de pierna sentadilla pistol",
"1489": "Sissy sentadilla",
"0735": "Abdominal V",
"3679": "Abdominal con arms en de pecho",
"3361": "Skater hops",
"2142": "Ski ergometer",
"3671": "Ski escalón",
"3304": "Skin cat",
"1425": "Degrees a una mano press de pierna trineo",
"0738": "De gemelos press trineo",
"0739": "Press de pierna trineo",
"1464": "Press de pierna de espalda pov trineo",
"1463": "Press de pierna lateral pov trineo",
"0740": "De pierna abierto press trineo",
"1391": "De gemelos press en press de pierna trineo",
"0741": "Closer hack sentadilla trineo",
"0742": "Forward angled elevación de gemelos trineo",
"0743": "Hack sentadilla trineo",
"2334": "Tumbado de gemelos press trineo",
"0744": "Tumbado sentadilla trineo",
"1392": "A una mano de pierna de gemelos press en press de pierna trineo",
"1496": "Sledge martillo",
"0746": "De espalda encogimiento smith",
"0747": "Behind de cuello press smith",
"0748": "Press de banca smith",
"0749": "Inclinado de rodilla buenos días smith",
"1359": "Remo inclinado smith",
"0750": "Chair sentadilla smith",
"0751": "Close-grip press de banca smith",
"0752": "Peso muerto smith",
"0753": "Declinado press de banca smith",
"0754": "Declinado reverse-grip press smith",
"1433": "Sentadilla frontal cargada agarre smith",
"3281": "Completo sentadilla smith",
"0755": "Hack sentadilla smith",
"0756": "De cadera elevación smith",
"0757": "Inclinado press de banca smith",
"0758": "Inclinado reverse-grip press smith",
"0759": "Inclinado de hombro raises smith",
"0760": "Press de pierna smith",
"1434": "Bajo sentadilla smith barra",
"1683": "Curl de bíceps máquina smith",
"1625": "Declinado agarre cerrado press de banca máquina smith",
"1752": "Inclinado extensión de tríceps máquina smith",
"1626": "Inverso declinado agarre cerrado press de banca máquina smith",
"0761": "Narrow remo smith",
"1360": "A una mano de brazo remo smith",
"1393": "A una mano de pierna en el suelo elevación de gemelos smith",
"0762": "Deltoides posterior remo smith",
"0763": "Inverso de gemelos raises smith",
"1394": "Inverso de gemelos raises smith",
"1361": "Agarre invertido remo inclinado smith",
"0764": "Reverse-grip press smith",
"1395": "Sentado a una mano de pierna elevación de gemelos smith",
"0765": "Sentado press de hombro smith",
"1426": "Sentado curl de muñeca smith",
"0766": "Press de hombro smith",
"0767": "Encogimiento smith",
"0768": "A una mano de pierna split sentadilla smith",
"0769": "Sprint zancada smith",
"0770": "Sentadilla smith",
"0771": "De pie de espalda curl de muñeca smith",
"0772": "De pie behind head military press smith",
"0773": "De pie de pierna elevación de gemelos smith",
"0774": "De pie military press smith",
"3142": "Sumo sentadilla smith",
"1396": "Toe elevación smith",
"0775": "Remo al mentón smith",
"1308": "Agarre abierto press de banca smith",
"1309": "Agarre abierto declinado press de banca smith",
"0776": "Arranque jalón",
"0777": "Spell caster",
"1362": "Sphinx",
"0778": "Spider crawl flexión",
"1363": "Columna estiramiento",
"2329": "Columna giro",
"2368": "Split squats",
"0786": "Sentadilla jerk",
"1705": "Sentadilla en bosu",
"1685": "Sentadilla a sobre la cabeza reach",
"1686": "Sentadilla a sobre la cabeza reach con giro",
"2297": "Pelota de estabilidad crunch completo range hands behind head",
"3291": "Stalder press",
"3669": "De pie archer",
"0788": "De pie behind de cuello press",
"1490": "De pie elevación de gemelos en a staircase",
"1397": "De pie calves",
"1398": "De pie calves de gemelos estiramiento",
"1599": "De pie de isquios y de gemelos estiramiento con strap",
"0794": "De pie lateral estiramiento",
"1364": "De pie pelvic tilt",
"0795": "De pie a una mano curl femoral",
"0796": "De pie wheel rollerout",
"3223": "Star salto",
"2138": "Stationary bike carrera V",
"0798": "Stationary bike caminata",
"3314": "Straddle maltese",
"3298": "Straddle planche",
"1427": "Recto de pierna externo de cadera abductor",
"0803": "Superman flexión",
"0805": "Suspended abdominal fallout",
"0806": "Suspended flexión",
"0807": "Suspended inverso crunch",
"0808": "Suspended remo",
"0809": "Suspended split sentadilla",
"3433": "Swimmer kicks V",
"3318": "Balanceo",
"1753": "Three bench fondo",
"2459": "Tire flip",
"0811": "Trapecio peso muerto barra",
"0814": "De tríceps fondo",
"0812": "De tríceps fondo bench de pierna",
"0813": "De tríceps fondo between benches",
"0815": "De tríceps dips en el suelo",
"0816": "De tríceps press",
"0817": "De tríceps estiramiento",
"0871": "Tuck crunch",
"0818": "Twin handle parallel agarre jalón al pecho",
"1466": "Giro de cadera levantamiento",
"2802": "Twisted elevación de piernas",
"2801": "Twisted elevación de piernas",
"3231": "A dos manos toe touch",
"1365": "Upper de espalda estiramiento",
"1366": "Upward facing dog",
"3420": "V-sit en en el suelo",
"0826": "Vertical elevación de piernas en parallel bars",
"2141": "Caminata elliptical cruzado trainer",
"3655": "Caminando alto knees zancada",
"1460": "Caminando zancada",
"3666": "Caminando en inclinado treadmill",
"2311": "Caminando en stepmill",
"0830": "Bench fondo lastrado",
"2987": "Agarre cerrado dominada supina en fondo cage lastrado",
"3643": "Cossack squats lastrado",
"0832": "Crunch lastrado",
"3670": "Declinado abdominal lastrado",
"0833": "Donkey elevación de gemelos lastrado",
"1310": "Drop flexión lastrado",
"2135": "Frontal plank lastrado",
"0834": "Elevación frontal lastrado",
"0866": "Colgado leg-hip elevación lastrado",
"0835": "Hyperextension en pelota de estabilidad lastrado",
"3641": "De rodillas escalón con balanceo lastrado",
"3644": "Zancada con balanceo lastrado",
"3286": "Muscle arriba lastrado",
"3312": "Muscle arriba en lastrado barra",
"3290": "A una mano hand dominada lastrado",
"0840": "Sobre la cabeza crunch en pelota de estabilidad lastrado",
"0841": "Dominada lastrado",
"0844": "Round de brazo lastrado",
"0846": "Giro ruso lastrado",
"0845": "Giro ruso legs arriba lastrado",
"2371": "Giro ruso V lastrado",
"0847": "Sentado curl de bíceps en pelota de estabilidad lastrado",
"0849": "Sentado giro en pelota de estabilidad lastrado",
"0850": "Flexión lateral en pelota de estabilidad lastrado",
"0851": "Sissy sentadilla lastrado",
"0852": "Sentadilla lastrado",
"0853": "De pie curl lastrado",
"0854": "De pie hand squeeze lastrado",
"3313": "Recto fondo lastrado barra",
"3642": "Estiramiento zancada lastrado",
"0856": "Svend press lastrado",
"1754": "Three bench dips lastrado",
"1755": "De tríceps dips lastrado",
"1767": "De tríceps fondo en alto parallel bars lastrado",
"0857": "Wheel rollerout",
"3637": "Wheel carrera",
"1429": "Agarre abierto dominada",
"1367": "Agarre abierto posterior dominada",
"1311": "Abierto hand flexión",
"2363": "Wide-grip de pecho fondo en alto parallel bars",
"0858": "Wind sprints",
"1604": "World greatest estiramiento",
"1428": "De muñeca círculos",
"0859": "De muñeca rollerer"
}
